<a href="https://colab.research.google.com/github/purushotham-del/COLAB-DL/blob/main/Dimensions_creating_and_manipulating_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
try:
 tf.executing_eagerly()
 print("TF imported with eager execution!")
except ValueError:
 print("TF already imported with eager execution!")
primes = tf.constant([11, 13, 17, 19, 23, 29], dtype=tf.int32)
print("primes:", primes)
ones = tf.ones([6], dtype=tf.int32)
print("ones:", ones)
just_beyond_primes = tf.add(primes, ones)
print("just_beyond_primes:", just_beyond_primes)
twos = tf.constant([7, 7, 7, 7, 7, 7], dtype=tf.int32)
primes_doubled = primes * twos
print("primes_doubled:", primes_doubled)
some_matrix = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.int32)
print(some_matrix)
print("\nvalue of some_matrix is:\n", some_matrix.numpy())

TF imported with eager execution!
primes: tf.Tensor([11 13 17 19 23 29], shape=(6,), dtype=int32)
ones: tf.Tensor([1 1 1 1 1 1], shape=(6,), dtype=int32)
just_beyond_primes: tf.Tensor([12 14 18 20 24 30], shape=(6,), dtype=int32)
primes_doubled: tf.Tensor([ 77  91 119 133 161 203], shape=(6,), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

value of some_matrix is:
 [[1 2 3]
 [4 5 6]]
